
import Head from "next/head"
import { Geist } from "next/font/google";
import { Geist_Mono } from "next/font/google";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout( {
    children,
    MetaTitle,
} : {
    children:React.ReactNode
    MetaTitle?:string
}){
    return (
        <>
        <Head>
            <title>{}</title>
            <title>{`Next Js - ${MetaTitle || ''}`}</title>
            
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={`${geistSans.variable} ${geistMono.variable} flex flex-col min-h-screen`}
        >
            <header className="bg-blue-300 text-black">
                <div className="container mx-auto flex justify-between items-center py-4 px-6">
                    <h1 className="text-2xl font-bold">Blog</h1>
                    <nav>
                    <ul className="flex space-x-6">
                        <li>
                        <Link href="/" className="hover:underline">
                            Home
                        </Link>
                        </li>
                        <li>
                        <Link href="/about" className="hover:underline">
                            About
                        </Link>
                        </li>
                    </ul>
                    </nav>
                </div>
            </header>

            <main className="flex-1 container mx-auto p-4">
                {children}
            </main>
            <footer className=" text-center bg-blue-300 py-4">
                <p>&copy; {new Date().getFullYear()} Your Company. All rights reserved.</p>
            </footer>
        </div>
            
        </>
    )
}